# Numpy Basics

In [2]:
import numpy as np

## Numpy Arrays

In [5]:
import numpy as np
l = [1, 2, 3, 4, 5, 6] # list

np_arr = np.array(l) # numpy array
# np.asarray(l) # Same as above

np_arr

array([1, 2, 3, 4, 5, 6])

In [4]:
type(np_arr)

numpy.ndarray

In [8]:
# number of dimentions
np_arr.ndim # 1 dimentional

1

In [17]:
arr1 = np.asarray([[1,2,3], ['a', 'b', 'c']])
arr1

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U21')

In [13]:
arr1.ndim # 2 dimentional

2

## Matrices

Matrix is sub-class of array

In [24]:
np_matrix = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
])

np_matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [28]:
type(np_matrix)

numpy.matrix

> Convert into array if it is not already in any form of array, note that matrix is also an array.

In [22]:
np.asanyarray(np_matrix) # already an array (matrix), so no change.

matrix([[1, 2, 3],
        [4, 5, 6]])

In [23]:
np.asarray(np_matrix) # Convert to array 

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2 = arr1

> Both arr1 and arr2 refrence to same array in memory if one is changed another will follow changes. `shallow copy`

In [28]:
arr1[0][1] = 5

arr2 # also changed

array([['1', '5', '100'],
       ['a', 'b', 'c']], dtype='<U21')

To actually create a copy of data we need to use `np.copy()` - deep copy

In [30]:
arr3 = np.copy(arr1)

arr3

array([['1', '5', '100'],
       ['a', 'b', 'c']], dtype='<U21')

In [31]:
arr1[0][0] = 200

arr3 # not changed

array([['1', '5', '100'],
       ['a', 'b', 'c']], dtype='<U21')

In [33]:
# Generate array from functions:
np.fromfunction(lambda x, y: x == y, (2,3))

array([[ True, False, False],
       [False,  True, False]])

We got the output this way:

shape of array = [2 x 3]

| | 0| 1| 2|
|---|--|--|--|
|0 | T| F| F|
|1 | F| T| F|

In [36]:
np.fromfunction(lambda i,j: i*j, (5,5), dtype=int)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [40]:
np.fromiter(range(10), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.fromstring('1, 2, 3, 4, 5', sep=', ', dtype=int) # pass only numbers.

array([1, 2, 3, 4, 5])

In [60]:
np_arr.size # number of elements

6

In [53]:
np_matrix.size

6

In [57]:
np_arr.shape

(6,)

In [56]:
np_matrix.shape

(2, 3)

> Range function can't take float as argument.

We might want to create an array of numbers for what we use `np.arange()`

In [61]:
np.arange(1.3, 2.6) # default increment = 1.0

array([1.3, 2.3])

In [63]:
np.arange(2.2, 3.7, 0.2)

array([2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6])

In [66]:
np.linspace(1, 3, 10) # 10 numbers from 1 to 3

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [67]:
np.logspace(2, 7, 5) # 5 logarithmic steps from 2 to 7

array([1.00000000e+02, 1.77827941e+03, 3.16227766e+04, 5.62341325e+05,
       1.00000000e+07])

In [69]:
np.logspace(2, 7, 10, base=2) # 10 logarithmic values from 2 to 7 using base as 2

array([  4.        ,   5.87893797,   8.64047791,  12.69920842,
        18.66446463,  27.43180745,  40.3174736 ,  59.25598159,
        87.09056001, 128.        ])

In [73]:
np.zeros(5, dtype=int) # Generate 5 zeros of type int (default is float)

array([0, 0, 0, 0, 0])

In [74]:
np.zeros((3, 4)) # 3 rows and 4 columns of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
np.ones(4)

array([1., 1., 1., 1.])

In [78]:
np.ones([2,4]) + 2 # add 2 to each element in the array

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [81]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [83]:
np.eye(4) # identity matrix: 4x4 matrix with 1's on the diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Convert array to dataframe:

In [85]:
import pandas as pd

pd.DataFrame(np.eye(3,4), columns=list('ABCD'), index=list('123'))

A    B    C    D
1  1.0  0.0  0.0  0.0
2  0.0  1.0  0.0  0.0
3  0.0  0.0  1.0  0.0

In [92]:
(np.random.rand(2, 2) * 10) # Generate random numbers between 0 and 10

array([[5.05034722, 1.43100964],
       [9.92193476, 4.3686235 ]])

In [127]:
# Normally distributed data:
# mean = 0 
# std = 1

np.random.randn(10)

array([ 0.85888304,  1.79954283,  1.10177377, -1.22708744,  0.0159787 ,
       -0.29915229,  1.53937394,  0.36283593, -0.33560344, -0.03813116])

In [137]:
random_int_array = np.random.randint(5, 10, size=(2,3))
random_int_array

array([[6, 7, 8],
       [6, 5, 5]])

In [141]:
random_int_array.reshape(3, 2) # 3 x 2 = 6

array([[6, 7],
       [8, 6],
       [5, 5]])

In [142]:
random_int_array.reshape(1, 6) # 1 x 6 = 6

array([[6, 7, 8, 6, 5, 5]])

In [143]:
random_int_array.reshape(6, 1) # 6 x 1 = 6

array([[6],
       [7],
       [8],
       [6],
       [5],
       [5]])

In [148]:
random_int_array.reshape(3, -1) # auto detect the number of columns (any negative number)

array([[6, 7],
       [8, 6],
       [5, 5]])

In [153]:
random_int_array.reshape(2, 3, -1)

array([[[6],
        [7],
        [8]],

       [[6],
        [5],
        [5]]])

In [158]:
random_int_array > 6 # if element is greater than 6

array([[False,  True,  True],
       [False, False, False]])

In [157]:
random_int_array[random_int_array > 6] # which elements are greater than 6?

array([7, 8])

In [164]:
random_int_array

array([[6, 7, 8],
       [6, 5, 5]])

In [160]:
random_int_array[0][:2]

array([6, 7])

In [163]:
random_int_array[0, [0, 1]] # Frist and second element from the first array among nested arrays

array([6, 7])

In [34]:
new_array = np.random.randint(2, 20, size=(6, 8))
new_array

array([[ 9,  9, 16, 18, 11, 19, 13, 11],
       [ 8,  8, 14,  9,  4, 14,  8, 16],
       [10,  8, 11, 19,  6, 15, 15,  7],
       [ 9,  4,  6,  8,  2, 12,  8, 18],
       [11,  7, 13,  2, 15, 12,  5, 13],
       [ 3,  9,  4,  3,  9,  6, 18,  9]])

In [35]:
new_array[2:4, [3,4]]

array([[19,  6],
       [ 8,  2]])

In [45]:
new_array1 = np.array(
    [[1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]]
)

new_array1[1:3, 3:5]

array([[ 9, 10],
       [14, 15]])

In [3]:
arr4 = np.random.randint(1, 10, (3, 3))
arr5 = np.random.randint(1, 10, (3, 3))

In [4]:
arr4

array([[5, 3, 3],
       [8, 5, 1],
       [2, 8, 2]])

In [5]:
arr5

array([[9, 4, 3],
       [8, 9, 6],
       [4, 3, 4]])

In [6]:
arr5 + arr4

array([[14,  7,  6],
       [16, 14,  7],
       [ 6, 11,  6]])

In [7]:
arr4 - arr5

array([[-4, -1,  0],
       [ 0, -4, -5],
       [-2,  5, -2]])

In [10]:
arr4 * arr5 
# Note that this is not matrix multiplication it is the multiplication of the corrsponding elements of the array.

array([[45, 12,  9],
       [64, 45,  6],
       [ 8, 24,  8]])

In [11]:
# Matrix multiplication
arr4@arr5

array([[ 81,  56,  45],
       [116,  80,  58],
       [ 90,  86,  62]])

## Numpy - Broadcasting

In [12]:
arr0 = np.zeros(shape=(3, 4))

In [13]:
arr0 + 2 # broadcasting 2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [16]:
arr0 + np.array([1, 2, 3, 4]) # Can't broadcast if columns not equal

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [18]:
arr0 + np.array([[1, 2, 3]]).T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [20]:
np.array([[1, 2, 3]]).T # this is why it is able to broadcast

array([[1],
       [2],
       [3]])

In [22]:
arr5.min()

3

In [23]:
np.min(arr5)

3