# More about Numpy

In [1]:
import numpy as np

## Array Manipulation in np

In [57]:
arr = np.random.randint(0,9, size=(4,4))
arr

array([[4, 3, 0, 8],
       [6, 0, 4, 0],
       [0, 3, 1, 5],
       [3, 0, 5, 8]])

In [18]:
np.expand_dims(arr, axis=0) # Converted to 3d across row

array([[[3, 8, 2, 4],
        [1, 1, 5, 2],
        [1, 3, 4, 2],
        [5, 3, 5, 8]]])

In [25]:
np.squeeze(np.array([[1], [2], [3]]))

array([1, 2, 3])

In [29]:
np.repeat(np.array([[1, 2, 3]]), repeats=3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
np.repeat(np.array([[1, 2, 3]]), repeats=3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [36]:
np.roll([1,3,4], shift=2)
# +2 to every index

# Before roll index of 1 is 0
# After roll index of 1 is 0+2 = 2
# Before roll index of 3 is 1
# After roll index of 3 is 1+2 = 3 but there is no 3 index so it moves to 0

array([3, 4, 1])

In [33]:
np.roll([1,3,4, 5, 8], 3)

array([4, 5, 8, 1, 3])

In [37]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [39]:
~arr # Binary negation

array([[-4, -9, -3, -5],
       [-2, -2, -6, -3],
       [-2, -4, -5, -3],
       [-6, -4, -6, -9]])

## String operations

In [40]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [41]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [42]:
np.char.upper(names)

array(['BOB', 'JOE', 'WILL', 'BOB', 'WILL', 'JOE', 'JOE'], dtype='<U4')

In [43]:
np.char.capitalize(names)

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

## Mathematical Operations

In [46]:
np.sin(arr) # sin value of each element

array([[ 0.14112001,  0.98935825,  0.90929743, -0.7568025 ],
       [ 0.84147098,  0.84147098, -0.95892427,  0.90929743],
       [ 0.84147098,  0.14112001, -0.7568025 ,  0.90929743],
       [-0.95892427,  0.14112001, -0.95892427,  0.98935825]])

In [47]:
np.cos(arr)

array([[-0.9899925 , -0.14550003, -0.41614684, -0.65364362],
       [ 0.54030231,  0.54030231,  0.28366219, -0.41614684],
       [ 0.54030231, -0.9899925 , -0.65364362, -0.41614684],
       [ 0.28366219, -0.9899925 ,  0.28366219, -0.14550003]])

In [48]:
np.tan(arr)

array([[-0.14254654, -6.79971146, -2.18503986,  1.15782128],
       [ 1.55740772,  1.55740772, -3.38051501, -2.18503986],
       [ 1.55740772, -0.14254654,  1.15782128, -2.18503986],
       [-3.38051501, -0.14254654, -3.38051501, -6.79971146]])

In [49]:
np.power(arr, 2)

array([[ 9, 64,  4, 16],
       [ 1,  1, 25,  4],
       [ 1,  9, 16,  4],
       [25,  9, 25, 64]])

## Statistical Opeerations

In [51]:
np.mean(arr)

3.5625

In [53]:
np.median(arr)

3.0

In [61]:
np.std(arr)

2.14967294023998

In [54]:
np.min(arr)

1

In [55]:
np.max(arr)

8

## Arithmatic Operations

In [59]:
np.mod(
    np.subtract(arr, 1), # subtract 1 from each element
    np.add(arr, 5) # add 5 to each element
) # Reminder

array([[2, 7, 1, 3],
       [0, 0, 4, 1],
       [0, 2, 3, 1],
       [4, 2, 4, 7]])

In [60]:
np.sqrt(arr)

array([[1.73205081, 2.82842712, 1.41421356, 2.        ],
       [1.        , 1.        , 2.23606798, 1.41421356],
       [1.        , 1.73205081, 2.        , 1.41421356],
       [2.23606798, 1.73205081, 2.23606798, 2.82842712]])

## Sort, Search, Counting

In [51]:
ssc_arr = np.array([6, 4, 2, 7, 23, 8, 9, 0])
ssc_arr

array([ 6,  4,  2,  7, 23,  8,  9,  0])

In [52]:
np.sort(ssc_arr)

array([ 0,  2,  4,  6,  7,  8,  9, 23])

In [53]:
np.searchsorted(ssc_arr, 3)
# where element should be inserted to maintain order.
# First element is 6 so 3 should be inserted before that = index 0.

3

In [54]:
np.searchsorted(np.sort(ssc_arr), 3)
# [0, *np.sort(ssc_arr)]

2

In [32]:
np.count_nonzero(ssc_arr)

7

In [55]:
np.where(ssc_arr < 4) # 2nd and 7th index

(array([2, 7]),)

In [59]:
arr

array([[4, 3, 0, 8],
       [6, 0, 4, 0],
       [0, 3, 1, 5],
       [3, 0, 5, 8]])

In [61]:
np.where(arr > 5)

(array([0, 1, 3]), array([3, 0, 3]))

In [64]:
np.extract(ssc_arr > 7, ssc_arr)

array([23,  8,  9])

## Numpy - Byte Swapping

In [69]:
ssc_arr[2:5].byteswap() # internal byte representation

array([ 144115188075855872,  504403158265495552, 1657324662872342528])

## Copies & Views

In [71]:
a = ssc_arr.copy() # deep copy
a

array([ 6,  4,  2,  7, 23,  8,  9,  0])

In [72]:
a = np.copy(ssc_arr)
a

array([ 6,  4,  2,  7, 23,  8,  9,  0])

In [76]:
b = ssc_arr.view() # shallow copy
b

array([ 5,  4,  2,  7, 23,  8,  9,  0])

In [74]:
b[0] = 5 
b

array([ 5,  4,  2,  7, 23,  8,  9,  0])

In [75]:
ssc_arr

array([ 5,  4,  2,  7, 23,  8,  9,  0])

## Matrix library

In [77]:
import numpy.matlib as nm

In [78]:
nm.zeros(5) # 2d = matrix (it doesn't give array)

matrix([[0., 0., 0., 0., 0.]])

In [79]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Linear algebra

In [87]:
a = np.random.randint([[2,3], [4,5]])
b = np.random.randint([[5,3], [2,5]])

In [88]:
a

array([[1, 1],
       [1, 0]])

In [89]:
b

array([[3, 0],
       [0, 1]])

In [93]:
np.dot(a, b) # dot product or matrix multiplication

array([[3, 1],
       [3, 0]])

In [92]:
a@b # same as above

array([[3, 1],
       [3, 0]])